In [2]:
import illustris_python as il
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import SymLogNorm
import h5py
from tqdm import tqdm

In [66]:
basePath = 'sims.TNG/TNG100-1/output'

snap = 99
halo_ID = 172650

tree  = il.sublink.loadTree(basePath,snap,halo_ID)
stars = il.snapshot.loadSubhalo(basePath,snap,halo_ID,'stars',['Coordinates','ParticleIDs','Masses'])

In [162]:
#### First, find all subhalos that come close to Main Progenitor ###

tree_main = il.sublink.loadTree(basePath, snap, halo_ID, fields=['SnapNum','SubfindID'], onlyMPB=True)
Snap_to_Subfind = dict(zip(tree_main['SnapNum'][::-1], tree_main['SubfindID'][::-1]))

lookup_subhalos = []
lookup_snapnum  = []
for s in tqdm(Snap_to_Subfind.keys(), leave=True):

    all_subhalos = il.groupcat.loadSubhalos(basePath,s,fields=['SubhaloHalfmassRad','SubhaloPos', 'SubhaloMass'])

    main_subhalo_halfmassrad = all_subhalos['SubhaloHalfmassRad'][Snap_to_Subfind[s]]
    virial_radius = main_subhalo_halfmassrad * 10

    all_subhalo_radius  = np.sum((all_subhalos['SubhaloPos']-all_subhalos['SubhaloPos'][Snap_to_Subfind[s]])**2,axis=1)**0.5

    subhalos_keep = np.where(all_subhalo_radius <= virial_radius)[0]

    lookup_subhalos.extend(subhalos_keep)
    lookup_snapnum.extend([s]*len(subhalos_keep))

np.savetxt(f'lookup_subhalos_{halo_ID}.txt', lookup_subhalos)
np.savetxt(f'lookup_snapnum_ {halo_ID}.txt', lookup_snapnum)

  9%|▉         | 9/99 [02:40<32:33, 21.71s/it]

In [ ]:
#### First, find all subhalos that come close to Main Progenitor ###

tree_main = il.sublink.loadTree(basePath, snap, halo_ID, fields=['SnapNum','SubfindID'], onlyMPB=True)
Snap_to_Subfind = dict(zip(tree_main['SnapNum'][::-1], tree_main['SubfindID'][::-1]))

lookup_subhalos = []
lookup_snapnum  = []
for s in tqdm(Snap_to_Subfind.keys(), leave=True):

    all_subhalos = il.groupcat.loadSubhalos(basePath,s,fields=['SubhaloHalfmassRad','SubhaloPos', 'SubhaloMass'])

    main_subhalo_halfmassrad = all_subhalos['SubhaloHalfmassRad'][Snap_to_Subfind[s]]
    virial_radius = main_subhalo_halfmassrad * 5

    all_subhalo_radius  = np.sum((all_subhalos['SubhaloPos']-all_subhalos['SubhaloPos'][Snap_to_Subfind[s]])**2,axis=1)**0.5

    subhalos_keep = np.where(all_subhalo_radius <= virial_radius)[0]

    lookup_subhalos.extend(subhalos_keep)
    lookup_snapnum.extend([s]*len(subhalos_keep))

np.savetxt(f'lookup_subhalos_{halo_ID}_rad5.txt', lookup_subhalos)
np.savetxt(f'lookup_snapnum_ {halo_ID}_rad5.txt', lookup_snapnum)

In [85]:
lookup_subhalos = np.loadtxt(f'lookup_subhalos_{halo_ID}.txt')
lookup_snapnum  = np.loadtxt(f'lookup_snapnum_ {halo_ID}.txt')

In [110]:
ID_init        = tree['SubhaloID'][0]
DescendantID   = tree['DescendantID'] - ID_init
tree_SubfinID  = tree['SubfindID']
tree_SubHaloID = tree['SubhaloID'] - ID_init

Subhalo_to_Subfind = dict(zip(tree_SubHaloID, tree_SubfinID))

subfind_descendant = tree_SubfinID[np.where(DescendantID <= 100)[0]]

In [118]:
np.isin(subfind_descendant, lookup_subhalos)

array([ True,  True,  True, ...,  True, False,  True])

In [119]:
subfind_descendant[-2]

175595

In [120]:
np.where(tree_SubfinID == 175595)

(array([50512]),)

In [130]:
(tree['SubhaloPos'][50512] **2).sum()**0.5-(tree['SubhaloPos'][1] **2).sum()**0.5

-53.99897072513704

In [128]:
(tree['SubhaloPos'][0] **2).sum()**0.5

72520.19018176939

In [109]:
tree_SubfinID

array([ 172650,  173164,  174699, ...,  175419, 2780422,  173229],
      dtype=int32)

In [92]:
DescendantID

array([-40000000600096289,                  0,                  1, ...,
                    50513,              50514,                  0])

In [95]:
np.isin(idx, lookup_subhalos)

array([False, False, False, ..., False, False, False])

In [86]:
lookup_subhalos

array([  9297.,   4811.,   6577., ..., 175210., 175211., 175216.])

In [83]:
!ls

 examples	   'lookup_snapnum_ 172650.txt'      README.txt
 illustris_idl	    lookup_subhalos_172650.txt	     sims.illustris
 illustris_julia    moreColors.png		     sims.other
 illustris_matlab   progenitorID_subhalo172650.txt   sims.TNG
 illustris_python   progenitorID_subhalo239993.txt   SubhaloID_stars.txt


In [57]:
subhalos_keep[0].shape

(180,)

In [36]:
subhalo_halfmassrad

9.209394

In [15]:
subhalos = il.groupcat.loadSubhalos(basePath,s,fields=['SubhaloFlag', 'SubhaloMass'])

In [17]:
subhalos['SubhaloMass'].max()

0.62153184

In [ ]:
progenitorID = np.zeros(stars['ParticleIDs'].shape) - 1
all_stars = stars['ParticleIDs']
# Iterate over all snapshots
for s in range(100):
    print(s)

    subhalos = il.groupcat.loadSubhalos(basePath,s,fields=['SubhaloFlag', 'SubhaloMass'])
    subfindID = np.where( (subhalos['SubhaloFlag'] == 1) & (subhalos['SubhaloMass'] >= 1) )[0]

    # Iterate over all subhalos
    for i in tqdm(subfindID, leave=True): 

        starsID_here = il.snapshot.loadSubhalo(basePath,s,i,'stars',['ParticleIDs'])
        
        not_already_IDed = np.where(progenitorID == -1)[0]
        stars_in = np.isin(all_stars[not_already_IDed], starsID_here)
        
        indices = not_already_IDed[stars_in]

        progenitorID[indices] = i


0


0it [00:00, ?it/s]


1


0it [00:00, ?it/s]


2


100%|██████████| 47/47 [00:02<00:00, 21.98it/s]


3


100%|██████████| 175/175 [00:06<00:00, 27.10it/s]


4


100%|██████████| 567/567 [00:16<00:00, 33.78it/s]


5


100%|██████████| 1100/1100 [00:32<00:00, 33.98it/s]


6


100%|██████████| 1626/1626 [00:46<00:00, 34.61it/s]


7


100%|██████████| 2761/2761 [01:14<00:00, 36.90it/s]


8


100%|██████████| 4171/4171 [01:48<00:00, 38.42it/s]


9


100%|██████████| 6002/6002 [02:36<00:00, 38.27it/s]


10


100%|██████████| 8091/8091 [03:31<00:00, 38.22it/s]


11


100%|██████████| 9783/9783 [04:09<00:00, 39.24it/s]


12


100%|██████████| 14206/14206 [06:23<00:00, 37.04it/s]


13


100%|██████████| 19907/19907 [08:55<00:00, 37.17it/s]


14


100%|██████████| 22172/22172 [10:10<00:00, 36.33it/s]


15


100%|██████████| 27048/27048 [12:53<00:00, 34.99it/s]


16


100%|██████████| 32280/32280 [15:49<00:00, 33.98it/s] 


17


100%|██████████| 36626/36626 [18:15<00:00, 33.43it/s] 


18


100%|██████████| 43240/43240 [21:50<00:00, 33.00it/s] 


19


100%|██████████| 48402/48402 [25:09<00:00, 32.06it/s] 


20


100%|██████████| 54110/54110 [28:25<00:00, 31.73it/s] 


21


100%|██████████| 58020/58020 [30:38<00:00, 31.57it/s] 


22


100%|██████████| 65009/65009 [34:18<00:00, 31.58it/s]  


23


100%|██████████| 69821/69821 [36:54<00:00, 31.53it/s]  


24


100%|██████████| 74327/74327 [37:20<00:00, 33.17it/s]  


25


100%|██████████| 80017/80017 [38:44<00:00, 34.42it/s]  


26


100%|██████████| 82125/82125 [38:23<00:00, 35.65it/s]  


27


100%|██████████| 85123/85123 [39:09<00:00, 36.22it/s]  


28


100%|██████████| 87662/87662 [38:15<00:00, 38.19it/s]  


29


100%|██████████| 89897/89897 [38:08<00:00, 39.28it/s]  


30


100%|██████████| 91832/91832 [38:36<00:00, 39.64it/s]  


31


100%|██████████| 93276/93276 [36:17<00:00, 42.84it/s]  


32


100%|██████████| 94612/94612 [35:49<00:00, 44.01it/s]  


33


100%|██████████| 95833/95833 [34:11<00:00, 46.71it/s]  


34


100%|██████████| 96926/96926 [35:03<00:00, 46.09it/s]  


35


100%|██████████| 97625/97625 [33:23<00:00, 48.73it/s]  


36


 25%|██▍       | 24366/98312 [13:12<29:58, 41.11it/s]  IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

100%|██████████| 98312/98312 [33:07<00:00, 49.48it/s] 


37


100%|██████████| 99284/99284 [33:45<00:00, 49.03it/s]  


38


100%|██████████| 99774/99774 [33:22<00:00, 49.83it/s]  


39


 38%|███▊      | 37845/100371 [18:38<25:00, 41.67it/s]  IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

 16%|█▌        | 15762/100633 [09:13<37:20, 37.88it/s]  IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

 41%|████▏     | 41546/100633 [19:57<23:16, 42.32it/s]

 69%|██████▉   | 69791/100633 [27:55<05:49, 88.27it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

 36%|███▌      | 36313/101158 [18:24<27:22, 39.47it/s]  IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

100%|██████████| 101158/101158 [34:02<00:00, 49.52it/s] 


42


  9%|▉         | 9578/101468 [06:02<46:40, 32.81it/s]  IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

 78%|███████▊  | 79211/101468 [28:59<03:19, 111.83it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

 43%|████▎     | 44103/101680 [20:16<17:44, 54.10it/s]  IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--Note

45


  4%|▍         | 3997/101908 [02:22<1:00:07, 27.14it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

 67%|██████▋   | 67807/101908 [25:07<06:20, 89.70it/s] IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

 39%|███▉      | 39857/102165 [17:14<21:02, 49.35it/s]  IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--Note

48


  1%|          | 1211/102320 [00:43<44:42, 37.70it/s]  IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

 63%|██████▎   | 64645/102320 [22:28<13:05, 47.94it/s] 


KeyboardInterrupt: 

In [ ]:
np.savetxt('text_progenitorID.txt', progenitorID, fmt='%d')